apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-server
  namespace: system
  labels:
    control-plane: controller-server
spec:
  selector:
    matchLabels:
      control-plane: controller-server
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-server
    spec:
      containers:
        - command:
            - /usr/local/bin/server
          image: controller:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8088
              name: http
          name: server
          resources:
            limits:
              cpu: 100m
              memory: 30Mi
            requests:
              cpu: 100m
              memory: 20Mi
      terminationGracePeriodSeconds: 10